### ISSUE TITLE
Crear branches para seguimiento y trabajo independiente del backend

### ISSUE THREAD

**Issue by altcamvi** [ISCOUTB/DG-CASGRADES#14]

**Comment by altcamvi** [comment]
Se crearon ramas para el trabajo independiente y se creó una rama 'main' donde se aloja el código fuente del proyecto en Flutter
![Image](https://github.com/user-attachments/assets/4557951d-e2b9-4c04-a021-f242fffd25fc)

**Comment by jairoserrano** [comment]
adelante
