### ISSUE TITLE
Taller de flutter

### ISSUE THREAD

**Issue by altcamvi** [ISCOUTB/DG-CASGRADES#7]

**Comment by aroldanc18** [comment]
En proceso

**Comment by aroldanc18** [comment]
Bueno muchachos, semana tras semana hemos venido trabajando y familiarizandonos con flutter, a continuacion breve explicacion de los que hemos hecho y visto para poder aprender sobre ello.
les comparto algunos recursos que fueron útiles para conocer más sobre Flutter, el framework que estamos utilizando para el desarrollo de nuestras aplicaciones. Flutter es un framework de UI de código abierto creado por Google, que permite desarrollar aplicaciones nativas para Android, iOS, web y escritorio con una única base de código. Su motor gráfico altamente optimizado y la rapidez con la que podemos crear interfaces hacen de Flutter una excelente opción para el desarrollo móvil.

A continuación, los links vistos por el grupo y cursos que nos ayudaron a familiarizarnos más con Flutter y a mejorar nuestras habilidades:
+ https://www.youtube.com/watch?v=7N-wDxe18PA
+ https://www.youtube.com/watch?v=zNmDOXbTugE&list=PLCKuOXG0bPi0sIn-nDsi7ma9OV6MEMkxj (curso completo flutter)
+ https://www.youtube.com/watch?v=BTubOBvfEUE

**Comment by aroldanc18** [comment]
Ya hemos completado la instalación de Flutter en el PC  y lo tenemos configurado en Visual Studio Code.
![Captura de pantalla 2024-09-16 022938](https://github.com/user-attachments/assets/6b866506-9762-4b5d-be1b-2299a0ce7aae)

**Comment by aroldanc18** [comment]
Se ha completado la configuración de la extensión de Flutter y se ha creado el código base de nuestra app.
![Image](https://github.com/user-attachments/assets/e6375ad1-c22e-4ca0-af92-1d0d2bbfc9fd)

**Comment by jairoserrano** [comment]
ok
