### ISSUE TITLE
Creación de Wireframe de la app

### ISSUE THREAD

**Issue by altcamvi** [ISCOUTB/DG-CASGRADES#8]

**Comment by altcamvi** [comment]
Para la creación del modelo para el wireframe se usaron las herramientas que ofrece la página balsamiq.cloud
![Image](https://github.com/user-attachments/assets/bd184519-faee-4d3f-bb8d-d9541f0f4d79)

**Comment by altcamvi** [comment]
Primero se diseñó un modelo preliminar de las funciones básicas de la app a desarrollar. A partir de esto, se da la creación de las pantallas del programa:
![Image](https://github.com/user-attachments/assets/f24c3032-81f2-42be-9270-6ec513f4af99)
![Image](https://github.com/user-attachments/assets/30407e17-68d1-4bfc-9634-80b35affd0c4)
![Image](https://github.com/user-attachments/assets/1a60c59e-7af7-454f-90c3-8e78ee54f285)
![Image](https://github.com/user-attachments/assets/98e5c02b-5065-431b-a1d0-ab5fc57cf74b)

**Comment by altcamvi** [comment]
Luego, con las herramientas de Balsamiq creamos la visualización de estas pantallas al usuario:
![Image](https://github.com/user-attachments/assets/e82c916c-88cd-45fe-8ced-2f8af4ee7c70)
![Image](https://github.com/user-attachments/assets/ecf2462e-e9ca-4c87-aaae-e85377de08ac)
![Image](https://github.com/user-attachments/assets/9967c1ac-3635-40d3-afc4-5092dd24e584)
![Image](https://github.com/user-attachments/assets/b82fbfea-4023-4887-953d-3a0549926174)

**Comment by altcamvi** [comment]
Estas pantallas están sujetas a cambios y mejoras, dependiendo de las funcionalidades de cada una de ellas.

**Comment by jairoserrano** [comment]
adelante
